#! /bin/bash

apt update 

echo 'alias ll="ls -al"' >> ~/.bashrc
echo 'alias occ="runuser --user www-data -- /var/www/html/occ"' >> ~/.bashrc
echo 'export OC_PASS=changethepassword' >> ~/.bashrc
source ~/.bashrc

occ app:install calendar
occ app:install spreed

occ config:system:set --value "" skeletondirectory
occ config:app:set --value "100 MB" files default_quota

occ group:add <group>
occ user:add <user> --password-from-env --group="<group>" 
